### ISSUE TITLE
Generated C# files, unsupported by Unity

### ISSUE THREAD

**Issue by CrazyMan-IK** [RainwayApp/bebop#126]
**Describe the bug**
Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater;
'NotNullAttribute' is inaccessible due to its protection level;

**To Reproduce**
1. Generate C# files from .bop
2. Go to 'Unity'
3. Use generated files
4. See compile errors

**Expected behavior**
Normal working code, without errors

**Bebop info:**
- Version: 2.2.2
- Runtime: .NET

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I am trying to use bebop on Unity along with a Node.JS server. On the server side, everything works, but unfortunately the generated C # files use syntax not supported by the Unity (Negated not patterns) and attributes (NotNull, DisallowNull, MaybeNull, AllowNull)

**Comment by AndrewMD5** [comment]
I can probably address this today with a language version flag on the compiler

**Comment by CrazyMan-IK** [comment]
That would be great

**Comment by AndrewMD5** [comment]
So I've fixed the codegen but there are still some manual steps to actually get code to successfully compile. I'm going to look into a writing a Unity plugin 

![image](https://user-images.githubusercontent.com/1297077/119597590-36f98b80-bd96-11eb-8c84-ddbbd24ebcdb.png)
