### ISSUE TITLE
Rust build when source path is read-only

### ISSUE THREAD

**Issue by giacomocariello** [RainwayApp/bebop#179]
**Is your feature request related to a problem? Please describe.**
In some build scenarios, the "src" path in rust is read-only (for instance in NixOS), therefore generated files should be placed in folder pointed by "OUT_DIR" environment variable. Such scenario is well-handled by other schema encoding crates like prost_build.

**Describe the solution you'd like**
In orther for this to happen, generated .rs files should be imported singularly with something like:
`include!(concat!(env!("OUT_DIR"), "bebop"))` inside a mod declaration (prost provides a dedicated macro for this, which under the hood does exactly this), but this is not currently possible due to inner docs (the ones starting with //!) produced by bebopc in the beginning of files. Therefore, I'd like to request a flag to disable inner doc comments.

**Comment by Eadword** [comment]
Just to confirm, when you say "inner doc comments" here you just mean the module docs at the beginning of the file, right?

**Comment by Eadword** [comment]
Also can you clarify if the only changes requested here are
1. out dir overrides via env var at build
2. disable mod docs via feature flag

**Comment by giacomocariello** [comment]
> Just to confirm, when you say "inner doc comments" here you just mean the module docs at the beginning of the file, right?

Exactly.

**Comment by giacomocariello** [comment]
> Also can you clarify if the only changes requested here are
> 
> 1. out dir overrides via env var at build

Yes. Please consider that current bebop strategy of creating mod.rs to allow the project to import all schemas at once won't work when writing to ${OUT_DIR} because it's not possible to force module paths dynamically. Therefore, the developer has to create modules one by one in source code and include source from generated paths (which is done with `include!(concat!(env!("OUT_DIR"), "bebop"))`. So for instance, my src/lib.rs could be:

```
pub mod schema {
    include!(concat!(env!("OUT_DIR"), "bebop"))
}
```

and my build.rs could be something like:

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR")?).join("bebop");
    bebop_tools::build_schema_dir("bebop", out);
    Ok(())
}
```


> 2. disable mod docs via feature flag

Yes.

**Comment by Eadword** [comment]
@giacomocariello Please verify my PR #181 will solve this for you.
