### ISSUE TITLE
Error: Cannot find module '...\node_modules\bebop\dest\index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by RobinBlomberg** [RainwayApp/bebop#50]
**Describe the bug**
The file **dest/index.js** is missing from the npm distribution due to the project's **.gitignore** file. Thus, the import fails in Node.js.

**To Fix:**
Remove .gitignore, run `npm run build`, and publish a new version.

**To Reproduce**
1. Follow the steps from [Getting Started with TypeScript](https://github.com/RainwayApp/bebop/wiki/Getting-Started-with-TypeScript).

**Expected behavior**
The command `node ./index.js` (from the guide above) should run successfully.

**Bebop info:**
- Version: 2.0.0
- Runtime: Node.js v14.3.0

**Desktop:**
 - OS: Windows 10 Home
 - Version: 2004 (19041.630)

**Comment by AndrewMD5** [comment]
Thanks for reporting this @RobinBlomberg. We're getting a fix out.

**Comment by lynn** [comment]
This should be fixed in the newly published version `bebop@2.0.2` and `bebop-tools@2.0.2`. So if you try the steps in the guide from the top again, it should work now. Can you confirm @RobinBlomberg?

**Comment by RobinBlomberg** [comment]
@lynn Works like a charm — thank you!

Didn't even know you could publish gitignored files to npm. Learning something every day.
