### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by aspenluxxxy** [RainwayApp/bebop#59]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a Rust library for this, as many Rust libraries and applications often attempt to maximize performance, and this would be a great boost to that.

**Describe the solution you'd like**
A Rust library implementing Bebop, using [serde](https://github.com/serde-rs/serde) as the (de)serialization framework.

**Comment by aspenluxxxy** [comment]
I'm willing to try making a prototype in my free time.

**Comment by AndrewMD5** [comment]
hi @aspenluxxxy -- code generation is pretty straight forward; if you want to give it a shot we're happy to provide some feedback. If you have any feedback on how we can make the API easier to use for code gen it would be appreciated.
