### ISSUE TITLE
How I want to use the List object

### ISSUE THREAD

**Issue by Alan-Lun** [RainwayApp/bebop#72]
`var one = Song.Encode(EncodeData);`
`//List<Song>`
`var multi = Song.Encode(ListEncodeData);`

**Comment by AndrewMD5** [comment]
It sounds like you want to be able to encode a list of `Song` objects. The simplest way would be to create a type that stores just that.

```
struct Library {
   Song[] songs;
}
```

Which would allow you to write

```csharp
var encodedLibrary = new Library {
   Songs = List<Song>.ToArray()
}.Encode();

var library = Library.Decode(encodedLibrary);
foreach (var song in library.Songs) {
   ...
}
```
